year: "2025"
theme: mountain
organizers:
- 中央研究院資訊科學研究所
- 國立臺灣大學電機工程學系
sponsors:
- 國立臺灣大學電機工程學系
programme:
- 陳郁方
- 王柏堯
local: 
- 暫無
ta_boss: 蔡瑋倫
ta:
- 羅芳毅
- 吳柏睿
- 吳宇璇
date: "8/11-8/22"
time: "09:10-12:10, 13:20–16:20"
