theme: mountain
year: "2021"
programme:
  - 陳郁方
date: "停辦"
time: ""

zh:
  title: 邏輯、語言與計算暑期研習營
  subtitle: Formosan Summer School on Logic, Language, and Computation
en:
  title: Formosan Summer School on Logic, Language, and Computation
  subtitle: 邏輯、語言與計算暑期研習營

announcements:
  - time: 6/1
    title: "本年度邏輯、語言與計算暑期研習營（FLOLAC）因應疫情停辦一年。"

calendar: 
  - time: 6/1
    date: "2021-06-01"
    title: 宣佈停辦
