theme: mountain
year: "2023"
programme:
  - 陳郁方
date: "08/21-09/01"
time: "09:00-17:00"

zh:
  title: 邏輯、語言與計算暑期研習營
  subtitle: Formosan Summer School on Logic, Language, and Computation
en:
  title: Formosan Summer School on Logic, Language, and Computation
  subtitle: 邏輯、語言與計算暑期研習營
