theme: mountain
year: "2023"
programme:
  - 陳郁方
date: "08/21-09/01"
time: "09:00-17:00"

zh:
  title: 邏輯、語言與計算暑期研習營
  subtitle: Formosan Summer School on Logic, Language, and Computation
en:
  title: Formosan Summer School on Logic, Language, and Computation
  subtitle: 邏輯、語言與計算暑期研習營

announcements: 
  - time: 05/31
    title: 網站上線
  - time: 08/15
    title: 上課地點台灣大學管理學院一號館101

calendar:
  - time: 05/31
    title: 網站上線
    past: true
  - time: 07/13
    title: 外校學生修課報名開始
    past: false
  - time: 07/14
    title: 外校學生修課報名截止
    past: false
  - time: 07/19
    title: 臺大學生報名開始
    past: false
  - time: 07/20
    title: 臺大學生報名截止
    past: false
  - time: 07/24
    title: 旁聽報名截止(07/31通知結果)
    past: false
  - time: 07/27
    title: 課程網路加退選截止
    past: false
  - time: 08/21
    title: 課程開始
    past: false
  - time: 08/28
    title: 期中停修截止
    past: false
  - time: 09/01
    title: 課程結束
    past: false
