year: "2024"
theme: ocean
organizers:
- 中央研究院資訊科學研究所
- 國立臺灣大學資訊管理學系
sponsors:
- 入山山有限公司
- 國立臺灣大學資訊工程學系
- 國立臺灣大學電機工程學系
programme:
- 柯向上
- 陳亮廷
- 穆信成
local:
- 林柏芬
- 韓愷真
ta_boss: 蔡子濬
ta:
- 林秉軒
- 陳正康
- 曾顯恩
- 蔡柏毅
- 薛盛安
- 張耀晟
date: "7/1-7/12"
time: "09:10-12:10, 13:20–16:20"

announcements:
- time: 08/13
  title: 寄出考試通過證書
- time: 07/30
  title: 寄出考試結果通知
- time: 06/12
  title: 發出旁聽錄取通知
- time: 06/10
  title: 發出台大學生修課錄取通知
- time: 06/06
  title: 發出非台大學生修課錄取／未錄取通知
- time: 05/10
  title: 公布<a href="registration.html">報名資訊</a>
- time: 01/26
  title: 更新<a href="registration.html#registration-information">外地實習生報名資訊</a>
- time: 01/26
  title: 網站上線

calendar:
- time: 01/26
  date: "2024-01-26"
  title: 網站上線
- time: 02/15
  date: "2024-02-15"
  title: 外地實習生報名開始
- time: 03/15
  date: "2024-03-15"
  title: 外地實習生報名截止
- time: 06/05
  date: "2024-06-05"
  title: 外校學生修課報名截止
- time: 06/09
  date: "2024-06-09"
  title: 台大學生正式報名截止
- time: 06/12
  date: "2024-06-12"
  title: 正式報名錄取回覆截止、台大學生候補報名截止、旁聽報名截止
- time: 06/13
  date: "2024-06-13"
  title: 候補報名錄取回覆截止
- time: 07/01
  date: "2024-07-01"
  title: 課程開始
- time: 07/09
  date: "2024-07-09"
  title: 期中停修截止
- time: 07/12
  date: "2024-07-12"
  title: 考試、課程結束
